version: '3'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: gunicorn oc_lettings_site.wsgi --bind 0.0.0.0:8080
    environment:
      - DJANGO_SETTINGS_MODULE=oc_lettings_site.settings
    expose:
      - "8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: always
