version: '3'

services:
  web:
    image: python:3.9-slim
    command: gunicorn oc_lettings_site.wsgi --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=oc_lettings_site.settings
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
