version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
     

      # Restore Python dependencies cache
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      
      # Install Python dependencies
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Save Python dependencies cache
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      # Run pytest
      # - run:
      #     name: Run pytest
      #     command: |
      #       source venv/bin/activate &&
      #       pip install --upgrade pip &&
      #       pytest

  deploy:
    docker:
      - image: python:3.8
    working_directory: /home/circleci/project
    steps:
      - checkout

      # Set AWS credentials
      - run:
          name: Set AWS credentials
          command: |
            aws configure set aws_access_key_id $AMAZON_ACCESS_KEY_ID && \
            aws configure set region $AMAZON_REGION

      # Verify AWS configuration
      - run:
          name: Verify AWS configuration
          command: aws configure list

      - run:
          name: Debug Environment Variables
          command: |
            echo "DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}"
            echo "CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}"
            echo "CIRCLE_SHA1: ${CIRCLE_SHA1}"

      # Authenticate with Docker Hub using access token
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      # Build Docker image using Dockerfile from project directory
      - run:
          name: Build Docker image
          command: |
            docker build --tag ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .

      # Push Docker image to DockerHub
      - run:
          name: Push Docker image to DockerHub
          command: docker push ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

      # SSH into EC2 instance, pull the latest Docker image, and run Docker Compose
      - run:
          name: Deploy using Docker Compose
          command: |
            ssh -i ~/.ssh/${LETTINGS_AMAZON_LINUX_KEY} ec2-user@EC2_PUBLIC_IP 'docker pull ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} && cd /home/ec2-user/${CIRCLE_PROJECT_REPONAME} && docker-compose up -d'

workflows:
  build_and_deploy_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
