version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.6

    working_directory: /home/circleci/project

    steps:
      - checkout

      # Install system dependencies
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install python3-venv docker-compose
            sudo apt-get -y install docker.io containerd

      # Fix broken packages
      - run:
          name: Fix broken packages
          command: |
            sudo apt-get install -f

      # Upgrade or install containerd
      - run:
          name: Upgrade or install containerd
          command: |
            sudo apt-get install containerd

      # Try installing docker.io again
      - run:
          name: Install docker.io again
          command: |
            sudo apt-get install docker.io

      # Verify docker installation
      - run:
          name: Verify docker installation
          command: |
            docker --version

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      # Run pytest
      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            pytest

  deploy:
    docker:
      - image: cimg/python:3.6

    working_directory: /home/circleci/project

    steps:
      - checkout

      # Build Docker image and tag it as lettings_app
      - run:
          name: Build Docker image
          command: |
            docker build -t lettings_app .

      # Authenticate with Docker Hub using access token
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      # Push Docker image to DockerHub
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker tag lettings_app $DOCKERHUB_USERNAME/lettings_app
            docker push $DOCKERHUB_USERNAME/lettings_app

      # Deploy using Docker Compose 
      - run:
          name: Deploy using Docker Compose
          command: |
            scp -i ~/.ssh/${LETTINGS_APP_EC2_KEY} lettings_app.tar.gz ubuntu@EC2_PUBLIC_IP:/home/ubuntu
            ssh -i ~/.ssh/{$LETTINGS_APP_EC2_KEY} ubuntu@EC2_PUBLIC_IP 'tar -xzvf lettings_app.tar.gz && cd lettings_app && docker-compose up -d'

workflows:
  build_and_deploy_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
