version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: python:3.8-slim-buster
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade --force-reinstall django
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run pytest
          command: |
            source venv/bin/activate && pytest

  containerise:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build --tag ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

  deploy-prod:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git

workflows:
  build_and_deploy_workflow:
    jobs:
      - build
      - containerise:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - containerise
          filters:
            branches:
              only:
                - master
