version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.6
    working_directory: /home/circleci/project
    steps:
      - checkout

      # Install system dependencies
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install python3-venv docker-compose
            sudo apt-get -y install docker.io containerd

      # Fix broken packages
      - run:
          name: Fix broken packages
          command: |
            sudo apt-get install -f

      # Upgrade or install containerd
      - run:
          name: Upgrade or install containerd
          command: |
            sudo apt-get install containerd

      # Try installing docker.io again
      - run:
          name: Install docker.io again
          command: |
            sudo apt-get install docker.io

      # Start Docker service with elevated privileges
      - run:
          name: Start Docker service
          command: |
            sudo nohup dockerd > /dev/null 2>&1 &

      # Wait for Docker service to start
      - run:
          name: Wait for Docker service
          command: |
            sleep 10

      # Verify docker installation
      - run:
          name: Verify docker installation
          command: |
            docker --version

      # Restore Python dependencies cache
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      
      # Install Python dependencies
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Save Python dependencies cache
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            
      # Run pytest
      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            pytest

  deploy:
    docker:
      - image: cimg/python:3.6
    working_directory: /home/circleci/project
    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get -y install awscli

      # Set AWS credentials
      - run:
          name: Set AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      
      # Verify AWS configuration
      - run:
          name: Verify AWS configuration
          command: |
            aws configure list

      - run:
          name: Debug Environment Variables
          command: |
            echo "DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME"
            echo "CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME"
            echo "CIRCLE_SHA1: $CIRCLE_SHA1"

      # Build Docker image using Dockerfile from project directory
      - run:
          name: Build and push Docker image to Docker Hub
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> ${BASH_ENV}
            echo 'export IMAGE_NAME=${CIRCLE_PROJECT_REPONAME}' >> ${BASH_ENV}
            source ${BASH_ENV}
            docker build tag ${DOCKER_LOGIN}/${IMAGE_NAME} tag ${DOCKER_LOGIN}/${IMAGE_NAME}:${TAG} .
            echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
            docker push ${DOCKER_LOGIN}/${IMAGE_NAME}

      # SSH into EC2 instance, pull the latest Docker image, and run Docker Compose
      - run:
          name: Deploy using Docker Compose
          command: |
            ssh -i ~/.ssh/${lettings_app_ec2_key} ubuntu@EC2_PUBLIC_IP 'docker pull $DOCKERHUB_USERNAME/${CIRCLE_PROJECT_REPONAME} && cd /home/ubuntu/${CIRCLE_PROJECT_REPONAME} && docker-compose up -d'

workflows:
  build_and_deploy_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
