# Generated by Django 3.0 on 2024-04-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addres',
        ),
    ]
    atomic = False
